# Generated by Django 2.2.16 on 2021-01-15 19:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('http_support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiclient',
            name='editors',
            field=models.ManyToManyField(related_name='http_api_client_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='apiclient',
            name='viewers',
            field=models.ManyToManyField(related_name='http_api_client_viewables', to=settings.AUTH_USER_MODEL),
        ),
    ]
