# pylint: skip-file

# Generated by Django 5.2.14 on 2026-05-08 19:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('http_support', '0002_auto_20210115_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'verbose_name': 'API client', 'verbose_name_plural': 'API clients'},
        ),
    ]