# pylint: disable=no-member, line-too-long

from django.contrib.auth.models import Group, Permission
from django.core.management.base import BaseCommand

class Command(BaseCommand):
    def handle(self, *args, **cmd_options): # pylint: disable=unused-argument, too-many-locals
        reader_group = Group.objects.get(name='Hive Mechanic Reader')
        reader_group.permissions.add(Permission.objects.get(name='Access Hive Mechanic game builder'))

        editor_group = Group.objects.get(name='Hive Mechanic Game Editor')
        editor_group.permissions.add(Permission.objects.get(name='Access Hive Mechanic game builder'))
        editor_group.permissions.add(Permission.objects.get(name='Can add game'))
        editor_group.permissions.add(Permission.objects.get(name='Can change game'))
        editor_group.permissions.add(Permission.objects.get(name='Can delete game'))
        editor_group.permissions.add(Permission.objects.get(name='Can view game'))
        editor_group.permissions.add(Permission.objects.get(name='Can add game version'))
        editor_group.permissions.add(Permission.objects.get(name='Can change game version'))
        editor_group.permissions.add(Permission.objects.get(name='Can delete game version'))
        editor_group.permissions.add(Permission.objects.get(name='Can view game version'))

        manager_group = Group.objects.get(name='Hive Mechanic Manager')
        manager_group.permissions.add(Permission.objects.get(name='Access Hive Mechanic game builder'))
        manager_group.permissions.add(Permission.objects.get(name='Can view group'))
        manager_group.permissions.add(Permission.objects.get(name='Can add user'))
        manager_group.permissions.add(Permission.objects.get(name='Can change user'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete user'))
        manager_group.permissions.add(Permission.objects.get(name='Can view user'))
        manager_group.permissions.add(Permission.objects.get(name='Can add game'))
        manager_group.permissions.add(Permission.objects.get(name='Can add game'))
        manager_group.permissions.add(Permission.objects.get(name='Can change game'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete game'))
        manager_group.permissions.add(Permission.objects.get(name='Can view game'))
        manager_group.permissions.add(Permission.objects.get(name='Can add game version'))
        manager_group.permissions.add(Permission.objects.get(name='Can change game version'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete game version'))
        manager_group.permissions.add(Permission.objects.get(name='Can view game version'))
        manager_group.permissions.add(Permission.objects.get(name='Can add interaction card'))
        manager_group.permissions.add(Permission.objects.get(name='Can change interaction card'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete interaction card'))
        manager_group.permissions.add(Permission.objects.get(name='Can view interaction card'))
        manager_group.permissions.add(Permission.objects.get(name='Can view integration'))
        manager_group.permissions.add(Permission.objects.get(name='Can add execution'))
        manager_group.permissions.add(Permission.objects.get(name='Can change execution'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete execution'))
        manager_group.permissions.add(Permission.objects.get(name='Can view execution'))
        manager_group.permissions.add(Permission.objects.get(name='Can add task'))
        manager_group.permissions.add(Permission.objects.get(name='Can change task'))
        manager_group.permissions.add(Permission.objects.get(name='Can delete task'))
        manager_group.permissions.add(Permission.objects.get(name='Can view task'))
        manager_group.permissions.add(Permission.objects.get(name='Can view incoming message'))
        manager_group.permissions.add(Permission.objects.get(name='Can view incoming message media'))
        manager_group.permissions.add(Permission.objects.get(name='Can view outgoing call'))
        manager_group.permissions.add(Permission.objects.get(name='Can view outgoing message'))
