# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0002_incomingcallresponse_outgoingcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingcall',
            name='end_call',
            field=models.BooleanField(default=False),
        ),
    ]
