# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-11 20:44


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0003_outgoingcall_end_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingcall',
            name='end_call',
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_finish_on_key',
            field=models.CharField(default='#', max_length=64),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_input',
            field=models.CharField(choices=[('dtmf speech', 'Speech and Key Presses'), ('dtmf', 'Key Presses'), ('speech', 'Speech')], default='dtmf speech', max_length=64),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_num_digits',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_speech_model',
            field=models.CharField(choices=[('default', 'Default'), ('numbers_and_commands', 'Numbers and Commands'), ('phone_call', 'Phone Call')], default='default', max_length=64),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_speech_profanity_filter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_speech_timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_timeout',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='next_action',
            field=models.CharField(choices=[('continue', 'Continue'), ('pause', 'Pause'), ('gather', 'Gather Response'), ('hangup', 'Hang Up')], default='continue', max_length=64),
        ),
        migrations.AddField(
            model_name='outgoingcall',
            name='pause_length',
            field=models.IntegerField(default=5),
        ),
    ]
