# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-16 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0005_incomingmessagemedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingcallresponse',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_incoming_calls', to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_incoming', to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='outgoingcall',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_outgoing_calls', to='integrations.Integration'),
        ),
        migrations.AlterField(
            model_name='outgoingmessage',
            name='integration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='twilio_outgoing', to='integrations.Integration'),
        ),
    ]
