# pylint: skip-file
# Generated by Django 3.2.7 on 2021-10-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0007_permissionssupport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingcall',
            name='start_call',
        ),
    ]
