# pylint: skip-file
# Generated by Django 3.2.7 on 2021-11-30 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0009_alter_incomingcallresponse_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outgoingcall',
            name='gather_speech_profanity_filter',
        ),
    ]
