# pylint: skip-file
# Generated by Django 3.2.7 on 2021-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0009_alter_incomingcallresponse_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outgoingcall',
            name='gather_finish_on_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingcall',
            name='gather_num_digits',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingcall',
            name='gather_speech_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='outgoingcall',
            name='gather_timeout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
