# pylint: skip-file
# Generated by Django 3.2.7 on 2021-12-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0010_remove_outgoingcall_gather_speech_profanity_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='outgoingcall',
            name='gather_loop',
            field=models.IntegerField(default=1),
        ),
    ]
