# pylint: skip-file
# Generated by Django 3.2.10 on 2021-12-29 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0010_auto_20211107_1440'),
        ('twilio_support', '0011_outgoingcall_gather_loop'),
    ]

    operations = [
    ]
