# pylint: skip-file
# Generated by Django 3.2.22 on 2023-10-20 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0013_auto_20220128_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingCallMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='incoming_call_media')),
                ('content_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('content_type', models.CharField(default='application/octet-stream', max_length=128)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='twilio_support.incomingcallresponse')),
            ],
        ),
    ]
