# pylint: skip-file
# Generated by Django 4.2.10 on 2024-03-08 20:18

import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twilio_support', '0014_incomingcallmedia'),
    ]

    if sys.version_info[0] > 2:
        operations = [
            migrations.AlterField(
                model_name='incomingcallresponse',
                name='transmission_metadata',
                field=models.JSONField(blank=True, default=dict, null=True),
            ),
            migrations.AlterField(
                model_name='incomingmessage',
                name='transmission_metadata',
                field=models.JSONField(blank=True, default=dict, null=True),
            ),
            migrations.AlterField(
                model_name='outgoingcall',
                name='transmission_metadata',
                field=models.JSONField(blank=True, default=dict, null=True),
            ),
            migrations.AlterField(
                model_name='outgoingmessage',
                name='transmission_metadata',
                field=models.JSONField(blank=True, default=dict, null=True),
            ),
        ]
    else:
        operations = []
