# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 20:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0003_player_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, unique=True)),
                ('url_slug', models.SlugField(max_length=1024, unique=True)),
                ('type', models.CharField(choices=[('twilio', 'Twilio'), ('other', 'Other')], default='twilio', max_length=1024)),
                ('configuration', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='builder.Game')),
            ],
        ),
    ]
