# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-03 15:22


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_integration_create_new_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('http', 'HTTP'), ('other', 'Other')], default='twilio', max_length=1024),
        ),
    ]
