# Generated by Django 2.2.16 on 2021-01-15 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0003_auto_20200403_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('integration_access_view', 'View integration information'), ('integration_access_edit', 'Edit integration information')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='integration',
            name='editors',
            field=models.ManyToManyField(related_name='integration_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integration',
            name='viewers',
            field=models.ManyToManyField(related_name='integration_viewables', to=settings.AUTH_USER_MODEL),
        ),
    ]
