# Generated by Django 2.2.16 on 2021-04-09 16:38

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_auto_20210115_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='configuration_help_text'),
        ),
    ]
