# pylint: skip-file
# Generated by Django 2.2.20 on 2021-06-09 21:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_auto_20210609_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='configuration_help_text', null=True),
        ),
    ]
