# pylint: skip-file
# Generated by Django 2.2.20 on 2021-06-09 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_auto_20210609_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='integration_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='integration',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='integration_viewables', to=settings.AUTH_USER_MODEL),
        ),
    ]
