# pylint: skip-file
# Generated by Django 2.2.20 on 2021-06-10 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0009_auto_20210609_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('http', 'HTTP'), ('command_line', 'Command Line'), ('other', 'Other')], default='twilio', max_length=1024),
        ),
    ]
