# pylint: skip-file
# Generated by Django 3.2.10 on 2022-01-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0010_auto_20210610_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
