# Generated by Django 4.2.18 on 2025-01-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0013_alter_integration_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='type',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('simple_messaging', 'Simple Messaging'), ('http', 'HTTP'), ('command_line', 'Command Line'), ('other', 'Other')], default='twilio', max_length=1024),
        ),
    ]
