# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 19:59


import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_interactioncard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=4096, unique=True)),
                ('player_state', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('completed', models.DateTimeField(blank=True, null=True)),
                ('session_state', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('game_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='builder.GameVersion')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='builder.Player')),
            ],
        ),
    ]
