# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_player_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactioncard',
            name='entry_actions',
            field=models.TextField(default='return []', max_length=1048576),
        ),
        migrations.AddField(
            model_name='interactioncard',
            name='evaluate_function',
            field=models.TextField(default='return None, [], None', max_length=1048576),
        ),
    ]
