# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20190712_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards',
            field=models.ManyToManyField(related_name='games', to='builder.InteractionCard'),
        ),
    ]
