# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0005_game_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactioncard',
            name='client_implementation',
            field=models.FileField(blank=True, null=True, upload_to='interaction_cards/'),
        ),
    ]
