# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0007_auto_20190813_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameversion',
            name='definition',
            field=models.TextField(max_length=1073741824),
        ),
    ]
