# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0009_game_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactioncard',
            name='metadata',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='interactioncard',
            name='repository_definition',
            field=models.TextField(blank=True, max_length=1048576, null=True),
        ),
        migrations.AddField(
            model_name='interactioncard',
            name='version',
            field=models.FloatField(default=0.0),
        ),
    ]
