# pylint: skip-file
# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0010_auto_20201106_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('url', models.URLField(max_length=4096, unique=True)),
                ('priority', models.IntegerField(default=0)),
                ('repository_definition', models.TextField(blank=True, max_length=1048576, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
