# pylint: skip-file
# Generated by Django 2.2.16 on 2021-01-15 19:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0011_remoterepository'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionsSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('builder_login', 'Access Hive Mechanic game builder'), ('builder_auth_access_view', 'View user account information'), ('builder_auth_access_edit', 'Edit user account information'), ('builder_access_view', 'View game builder information'), ('builder_access_edit', 'Edit game builder information'), ('builder_db_logging_view', 'View database logging entries'), ('builder_db_logging_edit', 'Edit database logging entries')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.AlterModelOptions(
            name='remoterepository',
            options={'verbose_name_plural': 'Remote Repositories'},
        ),
        migrations.AddField(
            model_name='game',
            name='editors',
            field=models.ManyToManyField(related_name='builder_game_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='game',
            name='viewers',
            field=models.ManyToManyField(related_name='builder_game_viewables', to=settings.AUTH_USER_MODEL),
        ),
    ]
