# Generated by Django 2.2.16 on 2021-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0012_auto_20210115_1957'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('builder_login', 'Access Hive Mechanic game builder'), ('builder_add_game', 'Add new Hive Mechanic game'), ('builder_auth_access_view', 'View user account information'), ('builder_auth_access_edit', 'Edit user account information'), ('builder_access_view', 'View game builder information'), ('builder_access_edit', 'Edit game builder information'), ('builder_db_logging_view', 'View database logging entries'), ('builder_db_logging_edit', 'Edit database logging entries'))},
        ),
    ]
