# pylint: skip-file
# Generated by Django 2.2.20 on 2021-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0014_auto_20210402_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('identifier', models.SlugField(max_length=4096, unique=True)),
                ('description', models.TextField(blank=True, max_length=16384, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('processor_function', models.TextField(default='return None, [], None', max_length=1048576)),
                ('metadata', models.TextField(blank=True, max_length=1048576, null=True)),
                ('repository_definition', models.TextField(blank=True, max_length=1048576, null=True)),
                ('version', models.FloatField(default=0.0)),
            ],
        ),
    ]
