# pylint: skip-file
# Generated by Django 3.2.7 on 2021-11-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0015_dataprocessor'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='activity_icons'),
        ),
    ]
