# pylint: skip-file
# Generated by Django 3.2.7 on 2021-12-10 17:38

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0017_sitesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='editors',
            field=models.ManyToManyField(blank=True, null=True, related_name='builder_game_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='viewers',
            field=models.ManyToManyField(blank=True, null=True, related_name='builder_game_viewables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gameversion',
            name='definition',
            field=models.TextField(blank=True, max_length=1073741824, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_state',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
