# pylint: skip-file
# Generated by Django 3.2.7 on 2021-12-10 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0018_auto_20211210_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='builder_game_editables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='builder_game_viewables', to=settings.AUTH_USER_MODEL),
        ),
    ]
