# pylint: skip-file
# Generated by Django 3.2.10 on 2021-12-28 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0018_game_is_template'),
        ('builder', '0019_auto_20211210_1738'),
    ]

    operations = [
    ]
