# pylint: skip-file
# Generated by Django 3.2.10 on 2022-01-13 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0020_merge_0018_game_is_template_0019_auto_20211210_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionCardCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('priority', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='interactioncard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.interactioncardcategory'),
        ),
    ]
