# pylint: skip-file
# Generated by Django 3.2.10 on 2022-01-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0021_auto_20220113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactioncardcategory',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
