# pylint: skip-file
# Generated by Django 3.2.10 on 2022-01-31 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_alter_interactioncardcategory_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='count_messages_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='total_message_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
