# pylint: skip-file
# Generated by Django 3.2.12 on 2022-02-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0023_auto_20220131_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameversion',
            name='cached_cytoscape',
            field=models.TextField(blank=True, max_length=1073741824, null=True),
        ),
    ]
