# pylint: skip-file
# Generated by Django 3.2.12 on 2022-03-14 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0024_gameversion_cached_cytoscape'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameversion',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
