# pylint: skip-file
# Generated by Django 3.2.12 on 2022-03-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0025_gameversion_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='message_of_the_day',
            field=models.TextField(default='Welcome to Hive Mechanic. You may customize this message in the site settings.', max_length=1048576),
        ),
    ]
