# pylint: skip-file
# Generated by Django 3.2.20 on 2023-08-29 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0026_sitesettings_message_of_the_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='total_message_limit',
            field=models.IntegerField(blank=True, help_text='Total of incoming and outgoing messages, plus voice calls', null=True),
        ),
    ]
