# pylint: skip-file
# Generated by Django 3.2.23 on 2023-12-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0028_auto_20230922_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProcessorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=4096)),
                ('requested', models.DateTimeField()),
                ('request_payload', models.TextField(max_length=4194304)),
                ('response_status', models.IntegerField()),
                ('response_payload', models.TextField(max_length=4194304)),
                ('data_processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_items', to='builder.dataprocessor')),
            ],
        ),
    ]
