# pylint: skip-file
# Generated by Django 3.2.23 on 2023-12-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0029_dataprocessorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessorlog',
            name='method',
            field=models.CharField(default='GET', max_length=4096),
        ),
    ]
