# pylint: skip-file
# Generated by Django 3.2.23 on 2024-01-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0030_dataprocessorlog_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessorlog',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_logs', to='builder.game'),
        ),
        migrations.AddField(
            model_name='dataprocessorlog',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_logs', to='builder.player'),
        ),
        migrations.AddField(
            model_name='dataprocessorlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processor_logs', to='builder.session'),
        ),
    ]
