# pylint: skip-file
# Generated by Django 3.2.23 on 2024-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0032_dataprocessorlog_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterepository',
            name='http_auth_headers',
            field=models.TextField(default='{}', max_length=1048576),
        ),
    ]
