# pylint: skip-file
# Generated by Django 3.2.23 on 2024-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0033_remoterepository_http_auth_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataprocessor',
            name='log_summary_function',
            field=models.TextField(default='return None', max_length=1048576),
        ),
    ]
