# pylint: skip-file
# Generated by Django 3.2.23 on 2024-02-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0034_dataprocessor_log_summary_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprocessor',
            name='log_summary_function',
            field=models.TextField(default='return None', help_text='Generates summary of data processor API calls, in a human-readable format.', max_length=1048576),
        ),
    ]
