# pylint: skip-file
# Generated by Django 3.2.23 on 2024-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0036_auto_20240205_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedfile',
            name='original_url',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
