# pylint: skip-file
# Generated by Django 4.2.10 on 2024-03-08 20:18

import sys

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0038_game_archived'),
    ]

    if sys.version_info[0] > 2:
        operations = [
            migrations.AlterField(
                model_name='game',
                name='game_state',
                field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
            ),
            migrations.AlterField(
                model_name='game',
                name='metadata',
                field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
            ),
            migrations.AlterField(
                model_name='player',
                name='player_state',
                field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
            ),
            migrations.AlterField(
                model_name='session',
                name='session_state',
                field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
            ),
        ]
    else:
        operations = []
