# pylint: skip-file
# Generated by Django 4.2.11 on 2024-03-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0039_alter_game_game_state_alter_game_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterepository',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
