# pylint: skip-file
# Generated by Django 4.2.11 on 2024-04-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0042_alter_statevariable_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='statevariable',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
