# pylint: skip-file
# Generated by Django 4.2.13 on 2024-06-21 18:24

import datetime
from django.db import migrations, models

try:
    from django.db.models import JSONField
except ImportError:
    from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0045_alter_permissionssupport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maximum_session_duration',
            field=models.DurationField(default=datetime.timedelta(days=14)),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_state',
            field=JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='game',
            name='metadata',
            field=JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_state',
            field=JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_state',
            field=JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='metadata',
            field=JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='statevariable',
            name='value',
            field=JSONField(blank=True, null=True),
        ),
    ]
