# pylint: skip-file
# Generated by Django 4.2.17 on 2024-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0046_sitesettings_maximum_session_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='new_player_message',
            field=models.TextField(default='The following messages are from Hive Mechanic. Reply STOP to opt out and stop any future messages.', max_length=1048576),
        ),
    ]
