# Generated by Django 4.2.18 on 2025-01-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0047_sitesettings_new_player_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='new_player_message',
            field=models.TextField(default='Incoming message from Hive Mechanic. Reply STOP to block further messages.', max_length=1048576),
        ),
    ]
