# pylint: skip-file
# Generated by Django 5.2.14 on 2026-05-08 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0048_alter_sitesettings_new_player_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='remoterepository',
            options={'verbose_name_plural': 'Remote repositories'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name_plural': 'Site settings'},
        ),
    ]