# Generated by Django 3.2.10 on 2022-01-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4096, unique=True)),
                ('tag', models.CharField(max_length=4096, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=4096)),
                ('message', models.TextField(max_length=4194304)),
                ('logged', models.DateTimeField()),
                ('metadata', models.TextField(max_length=4194304)),
                ('tags', models.ManyToManyField(blank=True, to='activity_logger.LogTag')),
            ],
        ),
    ]
