# pylint: skip-file
# Generated by Django 3.2.10 on 2022-01-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0022_alter_interactioncardcategory_priority'),
        ('activity_logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logitem',
            name='game_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.gameversion'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.player'),
        ),
        migrations.AddField(
            model_name='logitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='builder.session'),
        ),
    ]
