# pylint: skip-file
# Generated by Django 3.2.16 on 2022-11-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_logger', '0002_auto_20220114_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='log_items', to='activity_logger.LogTag'),
        ),
    ]
